modLoader="javafml"
license="MIT"
loaderVersion="[35,)"

[[mods]]
modId="sky"
version="1.2.0"
displayName="Sky"
description="Sky"
displayURL="http://suikacraft.com"
authors="yurisuika"

[[dependencies.sky]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
