modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="sky"
version="1.1.2"
displayName="Sky"
updateJSONURL="https://github.com/yurisuika/Sky/blob/master/updates.json"
displayURL="https://github.com/yurisuika/Sky"
authors="yurisuika"
logoFile="pack.png"
credits="yurisuika"
description="Sky - a sky dimension mod."

[[dependencies.sky]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
