modLoader="javafml"
license="MIT"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/yurisuika/Sky/issues"

[[mods]]
modId="sky"
version="1.2.4"
displayName="Sky"
updateJSONURL="https://raw.githubusercontent.com/yurisuika/Sky/master/updates.json"
displayURL="https://github.com/yurisuika/Sky"
logoFile="pack.png"
credits="yurisuika"
authors="yurisuika"
description="Sky - a sky dimension mod."

[[dependencies.sky]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
