modLoader="javafml"
license="MIT"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/yurisuika/Sky/issues"

[[mods]]
modId="sky"
version="1.2.1"
displayName="Sky"
updateJSONURL="https://github.com/yurisuika/Sky/blob/master/updates.json"
displayURL="https://github.com/yurisuika/Sky"
logoFile="pack.png"
credits="yurisuika"
authors="yurisuika"
description="Sky - a sky dimension mod."

[[dependencies.sky]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"
